


export type Firefighter = {
  id: string; // Firestore document ID (autogenerated, immutable)
  legajo: string;
  firstName: string;
  lastName: string;
  rank:
    | 'ASPIRANTE'
    | 'BOMBERO'
    | 'CABO'
    | 'CABO PRIMERO'
    | 'SARGENTO'
    | 'SARGENTO PRIMERO'
    | 'SUBOFICIAL PRINCIPAL'
    | 'SUBOFICIAL MAYOR'
    | 'OFICIAL AYUDANTE'
    | 'OFICIAL INSPECTOR'
    | 'OFICIAL PRINCIPAL'
    | 'SUBCOMANDANTE'
    | 'COMANDANTE'
    | 'COMANDANTE MAYOR'
    | 'COMANDANTE GENERAL';
  firehouse: string;
  status: 'Active' | 'Inactive';
};

export type AttendanceStatus = "present" | "absent" | "tardy" | "excused" | "recupero";

export type Session = {
  id: string;
  title: string;
  description: string;
  specialization: 'APH' | 'BUCEO' | 'FORESTAL' | 'FUEGO' | 'GORA' | 'HAZ-MAT' | 'KAIZEN' | 'PAE' | 'RESCATE' | 'VARIOS';
  date: string;
  startTime: string;
  instructors: Firefighter[];
  assistants: Firefighter[];
  attendees: Firefighter[];
  instructorIds?: string[];
  assistantIds?: string[];
  attendeeIds?: string[];
  attendance?: Record<string, AttendanceStatus>; // Firefighter ID -> Status
};

export type LeaveType = 'Ordinaria' | 'Extraordinaria' | 'Sanción' | 'Enfermedad' | 'Estudio' | 'Maternidad';

export type Leave = {
  id: string;
  firefighterId: string; // The immutable Firestore document ID
  firefighterName: string; // Storing for easier display
  startDate: string;
  endDate: string;
  type: LeaveType;
};

export type Course = {
  id: string;
  firefighterId: string;
  firefighterName: string;
  firefighterLegajo: string;
  specialization: Session['specialization'];
  title: string;
  location: string;
  startDate: string;
  endDate: string;
}

export type AttendanceModuleRole = 'Administrador' | 'Oficial' | 'Operador' | 'Ayudantía' | 'Bombero' | 'Ninguno';
export type WeekModuleRole = 'Administrador' | 'Oficial' | 'Encargado' | 'Bombero' | 'Ninguno';
export type MobilityModuleRole = 'Administrador' | 'Oficial' | 'Operador' | 'Bombero' | 'Ninguno';

export type User = {
  id: string; // This is the user's legajo
  name: string;
  password: string;
  role: 'Master' | 'Usuario'; // Global role
  roles: {
    asistencia: AttendanceModuleRole;
    semanas: WeekModuleRole;
    movilidad: MobilityModuleRole;
  };
};

// Tipo para el usuario logueado, puede ser nulo si no está autenticado
export type LoggedInUser = Omit<User, 'password'> | null;


// Types for "Semanas" Module
export type Week = {
    id: string;
    name: string;
    firehouse: 'Cuartel 1' | 'Cuartel 2' | 'Cuartel 3';
    periodStartDate: string;
    periodEndDate: string;
    leadId: string; // Firefighter ID of the week lead
    driverId: string; // Firefighter ID of the driver
    memberIds: string[]; // List of firefighter IDs in the week (excluding lead and driver)
    allMemberIds: string[]; // List of ALL firefighter IDs in the week
    observations: string; // For the "Pizarra de Novedades"
    // Enriched properties for client side
    lead?: Firefighter;
    driver?: Firefighter;
    members?: Firefighter[];
    allMembers?: Firefighter[]; // Includes lead, driver, and members
}

export type Task = {
    id: string;
    weekId: string;
    title: string;
    description: string;
    assignedToIds: string[]; // List of firefighter IDs assigned to the task
    status: 'Pendiente' | 'En Progreso' | 'Completada';
    // Enriched properties for client side
    assignedTo?: Firefighter[];
}
