

export type Firefighter = {
  id: string; // Firestore document ID (autogenerated, immutable)
  legajo: string;
  firstName: string;
  lastName: string;
  rank:
    | 'ASPIRANTE'
    | 'BOMBERO'
    | 'CABO'
    | 'CABO PRIMERO'
    | 'SARGENTO'
    | 'SARGENTO PRIMERO'
    | 'SUBOFICIAL PRINCIPAL'
    | 'SUBOFICIAL MAYOR'
    | 'OFICIAL AYUDANTE'
    | 'OFICIAL INSPECTOR'
    | 'OFICIAL PRINCIPAL'
    | 'SUBCOMANDANTE'
    | 'COMANDANTE'
    | 'COMANDANTE MAYOR'
    | 'COMANDANTE GENERAL';
  firehouse: string;
  status: 'Active' | 'Inactive';
};

export type AttendanceStatus = "present" | "absent" | "tardy" | "excused" | "recupero";

export type Specialization = 'APH' | 'BUCEO' | 'FORESTAL' | 'FUEGO' | 'GORA' | 'HAZ-MAT' | 'KAIZEN' | 'PAE' | 'RESCATE' | 'VARIOS';

export type Session = {
  id: string;
  title: string;
  description: string;
  specialization: Specialization;
  date: string;
  startTime: string;
  instructors: Firefighter[];
  assistants: Firefighter[];
  attendees: Firefighter[];
  instructorIds?: string[];
  assistantIds?: string[];
  attendeeIds?: string[];
  attendance?: Record<string, AttendanceStatus>; // Firefighter ID -> Status
};

export type LeaveType = 'Ordinaria' | 'Extraordinaria' | 'Enfermedad' | 'Estudio' | 'Maternidad';

export type Leave = {
  id: string;
  firefighterId: string; // The immutable Firestore document ID
  firefighterName: string; // Storing for easier display
  startDate: string;
  endDate: string;
  type: LeaveType;
};

export type Sanction = {
  id: string;
  firefighterId: string;
  firefighterName: string;
  startDate: string;
  endDate: string;
  reason: string;
};

export type Course = {
  id: string;
  firefighterId: string;
  firefighterName: string;
  firefighterLegajo: string;
  specialization: Specialization;
  title: string;
  location: string;
  startDate: string;
  endDate: string;
}

export type Vehicle = {
  id: string;
  numeroMovil: string;
  marca: string;
  modelo: string;
  ano: number;
  kilometraje: number;
  cuartel: 'Cuartel 1' | 'Cuartel 2' | 'Cuartel 3';
  especialidad: Specialization;
  capacidadAgua: number;
  tipoVehiculo: 'Liviana' | 'Mediana' | 'Pesada' | 'Cisterna';
  traccion: 'Trasera' | 'Delantera' | '4x4';
  encargadoIds: string[]; // Firefighter IDs of the people in charge
  observaciones: string;
  maintenanceItemIds?: string[]; // IDs of MaintenanceItem that apply to this vehicle
  // Enriched properties for client side
  encargados?: Firefighter[];
  maintenanceItems?: MaintenanceItem[];
}

export type MaintenanceChecklistItem = {
  name: string;
  checked: boolean;
};

export type MaintenanceRecord = {
  id: string;
  vehicleId: string;
  date: string; // Date of service
  mileage: number; // Mileage at service
  nextServiceDate?: string;
  nextServiceMileage?: number;
  checklist: MaintenanceChecklistItem[];
  observations: string;
};

export type MaintenanceItem = {
    id: string;
    name: string;
};

export type Material = {
  id: string;
  codigo: string;
  nombre: string;
  tipo: 'Lanza' | 'Manga' | 'Corte' | 'Combustion' | 'Hidraulica' | 'Golpe';
  especialidad: Specialization;
  caracteristicas?: string;
  ubicacion: {
    type: 'vehiculo' | 'deposito';
    vehiculoId?: string; // Firestore ID of the vehicle
    baulera?: string; // Name/number of the storage compartment
    deposito?: 'Cuartel 1' | 'Cuartel 2' | 'Cuartel 3';
  };
  estado: 'En Servicio' | 'Fuera de Servicio';
  condicion: 'Bueno' | 'Regular' | 'Malo';
  cuartel: 'Cuartel 1' | 'Cuartel 2' | 'Cuartel 3';
  // Enriched properties for client side
  vehiculo?: Vehicle;
}


export type AttendanceModuleRole = 'Administrador' | 'Oficial' | 'Instructor' | 'Ayudantía' | 'Bombero' | 'Ninguno';
export type WeekModuleRole = 'Administrador' | 'Oficial' | 'Encargado' | 'Bombero' | 'Ninguno';
export type MobilityModuleRole = 'Administrador' | 'Oficial' | 'Encargado Móvil' | 'Ninguno';
export type MaterialesModuleRole = 'Administrador' | 'Oficial' | 'Encargado' | 'Bombero' | 'Ninguno';
export type AyudantiaModuleRole = 'Ayudantía' | 'Oficial' | 'Master';

export type GlobalRole = 'Master' | 'Usuario';

export type User = {
  id: string; // This is the user's legajo
  name: string;
  password: string;
  role: GlobalRole; // Global role
  roles: {
    asistencia: AttendanceModuleRole;
    semanas: WeekModuleRole;
    movilidad: MobilityModuleRole;
    materiales: MaterialesModuleRole;
  };
};

// Tipo para el usuario logueado, puede ser nulo si no está autenticado
export type LoggedInUser = Omit<User, 'password'> | null;


// Types for "Semanas" Module
export type Week = {
    id: string;
    name: string;
    firehouse: 'Cuartel 1' | 'Cuartel 2' | 'Cuartel 3';
    periodStartDate: string;
    periodEndDate: string;
    leadId: string; // Firefighter ID of the week lead
    driverId: string; // Firefighter ID of the driver
    memberIds: string[]; // List of firefighter IDs in the week (excluding lead and driver)
    allMemberIds: string[]; // List of ALL firefighter IDs in the week
    observations: string; // For the "Pizarra de Novedades"
    // Enriched properties for client side
    lead: Firefighter | null;
    driver: Firefighter | null;
    members?: Firefighter[];
    allMembers?: Firefighter[]; // Includes lead, driver, and members
}

export type Task = {
    id: string;
    weekId: string;
    title: string;
    description: string;
    assignedToIds: string[]; // List of firefighter IDs assigned to the task
    status: 'Pendiente' | 'Completada';
    createdAt: string | null; // Changed to be consistently a string or null
    // Enriched properties for client side
    assignedTo?: Firefighter[];
}

// Audit Log Type
export type AuditLogAction = 
  | 'CREATE_USER' | 'UPDATE_USER' | 'DELETE_USER'
  | 'CREATE_FIREFIGHTER' | 'UPDATE_FIREFIGHTER' | 'DELETE_FIREFIGHTER' | 'BATCH_IMPORT_FIREFIGHTERS'
  | 'CREATE_SESSION' | 'UPDATE_SESSION' | 'DELETE_SESSION' | 'UPDATE_ATTENDANCE'
  | 'CREATE_LEAVE' | 'UPDATE_LEAVE' | 'DELETE_LEAVE'
  | 'CREATE_SANCTION' | 'UPDATE_SANCTION' | 'DELETE_SANCTION'
  | 'CREATE_COURSE' | 'UPDATE_COURSE' | 'DELETE_COURSE'
  | 'CREATE_WEEK' | 'UPDATE_WEEK' | 'DELETE_WEEK'
  | 'CREATE_TASK' | 'UPDATE_TASK' | 'DELETE_TASK'
  | 'CREATE_VEHICLE' | 'UPDATE_VEHICLE' | 'DELETE_VEHICLE'
  | 'CREATE_MAINTENANCE_RECORD' | 'DELETE_MAINTENANCE_RECORD'
  | 'CREATE_MATERIAL' | 'UPDATE_MATERIAL' | 'DELETE_MATERIAL'
  | 'LOGIN_SUCCESS' | 'LOGIN_FAILURE';

export type AuditLog = {
    id: string;
    timestamp: any; // Firestore ServerTimestamp
    userId: string;
    userName: string;
    action: AuditLogAction;
    targetEntity: string;
    targetId: string;
    details?: Record<string, any>;
};
